import "./globals.css";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["700", "500"],
  subsets: ["latin", "latin-ext"],
});

export const metadata = {
  title: "HEART WINK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-red_main`}>
        {children}
      </body>
    </html>
  );
}
