import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


import { Poppins} from "next/font/google"

const poppins = Poppins({
  weight: ["700", "500"],
  subsets: ["latin", "latin-ext"]
  
})



export const metadata: Metadata = {
  title: "HEART WINK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-red_main`}
      >
        {children}
      </body>
    </html>
  );
}
